"""added otp fields

Revision ID: fa684a3902a5
Revises: 
Create Date: 2025-10-09 07:20:24.033008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa684a3902a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add OTP and token columns to users table (safe, non-destructive)
    # If the columns already exist, Alembic will raise; run checks before applying in production.
    try:
        op.add_column('users', sa.Column('verification_token', sa.VARCHAR(), nullable=True))
    except Exception:
        # column may already exist
        pass
    try:
        op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), nullable=True))
    except Exception:
        pass
    try:
        op.add_column('users', sa.Column('otp_code', sa.VARCHAR(), nullable=True))
    except Exception:
        pass
    try:
        op.add_column('users', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    except Exception:
        pass
    # Ensure index on email exists (create if missing)
    try:
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('movies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='movies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('screens',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('screens_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='screens_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('showtime_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seats_booked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], name=op.f('bookings_showtime_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_table('showtimes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('screen_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('showtimes_movie_id_fkey')),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('showtimes_screen_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('showtimes_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verification_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
